// <auto-generated />
using System;
using MQ.DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MQ.DB.Migrations
{
    [DbContext(typeof(MagicQuantContext))]
    [Migration("20260503224957_PredictionEngineAnomalyDetect2")]
    partial class PredictionEngineAnomalyDetect2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImatrixDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Ngl")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TokensPerSecond")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("ImatrixDefinitionId");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "TensorComboId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "AiModelHashId", "ImatrixDefinitionId", "TensorComboId")
                        .IsUnique();

                    b.ToTable("AiBenchmarks");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmarkLearnedSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineCanonicalKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaselineQuantDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceLearningBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("TensorGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaselineQuantDefinitionId");

                    b.HasIndex("SourceLearningBenchmarkId");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("AiBenchmarkId", "TensorGroupId")
                        .IsUnique();

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "BaselineQuantDefinitionId");

                    b.ToTable("AiBenchmarkLearnedSources");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiModelHash", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniqueHash");

                    b.ToTable("AiModelHashes");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyInteractionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AppliedPredictionSpaceAdjustmentKld")
                        .HasColumnType("REAL");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BenchmarkCategory")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BestActualGainVsTwin")
                        .HasColumnType("REAL");

                    b.Property<double>("BestPredictionSpaceGap")
                        .HasColumnType("REAL");

                    b.Property<string>("CandidateDisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateEffectiveGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateInternalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullTensorConfigKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupSetHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImatrixDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InactiveGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MeanActualGainVsTwin")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanPredictionSpaceGap")
                        .HasColumnType("REAL");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementClassification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceContextKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceDisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceEffectiveGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceInternalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<byte>("ReferenceQuantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleDirection")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("ShrinkFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("FullTensorConfigKey");

                    b.HasIndex("ImatrixDefinitionId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "AiModelHashId", "ImatrixDefinitionId", "BenchmarkCategory", "RuleDirection", "RuleStatus");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "AiModelHashId", "ImatrixDefinitionId", "BenchmarkCategory", "ReferenceQuantId", "ReferenceContextKey", "GroupSetHash", "RuleDirection")
                        .IsUnique();

                    b.ToTable("AnomalyInteractionRules");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyInteractionRuleGroupState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("CandidateQuantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte>("ReferenceQuantId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TensorGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "TensorGroupId")
                        .IsUnique();

                    b.ToTable("AnomalyInteractionRuleGroupStates");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyProbeObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualGainVsTwin")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualKld")
                        .HasColumnType("REAL");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllActiveGroupsExplicit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BenchmarkCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidateEffectiveGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateQuantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedGroupSetHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DowngradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HypothesisLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImatrixDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InactiveGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContextualAnomalyProbe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementClassification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("NetBitDelta")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OldBf16Isolation")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PredictedKld")
                        .HasColumnType("REAL");

                    b.Property<double>("PredictionSpaceGapVsTwin")
                        .HasColumnType("REAL");

                    b.Property<string>("ProbeDisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbeInternalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbePlanClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProbeTensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbeTensorConfigKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("ReferenceActualKld")
                        .HasColumnType("REAL");

                    b.Property<string>("ReferenceDisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceEffectiveGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceInternalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("ReferencePredictedKld")
                        .HasColumnType("REAL");

                    b.Property<byte>("ReferenceQuantId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReferenceTensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceTensorConfigKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleDirection")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SameCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeedClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeedPriority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("SizeSavingsBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("ImatrixDefinitionId");

                    b.HasIndex("ProbeTensorComboId");

                    b.HasIndex("ProbeTensorConfigKey");

                    b.HasIndex("ReferenceTensorComboId");

                    b.HasIndex("ReferenceTensorConfigKey");

                    b.HasIndex("SessionId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "AiModelHashId", "ImatrixDefinitionId", "BenchmarkCategory", "ChangedGroupSetHash");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "AiModelHashId", "ImatrixDefinitionId", "BenchmarkCategory", "ReferenceTensorComboId", "ProbeTensorComboId", "ProbeType");

                    b.ToTable("AnomalyProbeObservations");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyProbeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BenchmarkCategory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImatrixDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceRunLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("ImatrixDefinitionId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "AiModelHashId", "ImatrixDefinitionId", "BenchmarkCategory", "StartedUtc");

                    b.ToTable("AnomalyProbeSessions");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.ArchitectureFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TensorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TensorSignatureHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("TensorSignatureHash", "TensorCount");

                    b.ToTable("ArchitectureFamilies");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.ArchitectureFamilyModelHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanonical")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiModelHashId")
                        .IsUnique();

                    b.HasIndex("ArchitectureFamilyId", "AiModelHashId")
                        .IsUnique();

                    b.ToTable("ArchitectureFamilyModelHashes");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.BaselineQuantDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineFamily")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte>("BitRange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<byte>("DefaultTensorSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultTensorSchemeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExplicitCandidateSortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiveInCurrentConfig")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCombinationCarrierCandidate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCustomBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExplicitGroupCombinationCandidate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLearningBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCanonicalKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSourceFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSourceRepository")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantizeBaseArgumentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresImatrix")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RuntimeBaselineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortSourceName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRepository")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActiveInCurrentConfig");

                    b.HasIndex("ArchitectureFamilyId", "NormalizedCanonicalKey")
                        .IsUnique();

                    b.HasIndex("ArchitectureFamilyId", "RuntimeBaselineId")
                        .IsUnique();

                    b.HasIndex("RuntimeBaselineId", "ArchitectureFamilyId");

                    b.HasIndex("ArchitectureFamilyId", "NormalizedSourceRepository", "NormalizedSourceFileName")
                        .IsUnique();

                    b.ToTable("BaselineQuantDefinitions");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.BenchmarkRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CategoryBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImatrixDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("ArchitectureFamilyId");

                    b.HasIndex("CategoryBenchmarkId");

                    b.HasIndex("ImatrixDefinitionId");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("AiBenchmarkId", "Category");

                    b.ToTable("BenchmarkRuns");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.CategoryBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kld")
                        .HasColumnType("REAL");

                    b.Property<double>("Ppl")
                        .HasColumnType("REAL");

                    b.Property<double>("PplError")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.ToTable("CategoryBenchmark");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.ExecutionPlanProbeCache", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscoveryTokenTarget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GpuMemoryLimitsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareFingerprint")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImatrixDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCandidateNgl")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("NativeModelSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeQuantizationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("NativeStableNgl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProbeSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Q8ModelSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q8StableNgl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuantizationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantizedModelFingerprint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("StaticNgl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TensorSplitJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsesGpu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("ArchitectureFamilyId");

                    b.HasIndex("ImatrixDefinitionId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "AiModelHashId", "ImatrixDefinitionId", "HardwareFingerprint", "QuantizedModelFingerprint", "QuantizationKey", "DiscoveryTokenTarget")
                        .IsUnique();

                    b.ToTable("ExecutionPlanProbeCaches");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.ImatrixDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildFingerprint")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiModelHashId", "IdentityHash")
                        .IsUnique();

                    b.ToTable("ImatrixDefinitions");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.LearnedBaselineTensorQuant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineCanonicalKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaselineQuantDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BaselineQuantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineSourceFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineSourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineSourceRepository")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalQuantType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("TensorGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TensorName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<byte>("TensorWeightSchemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("BaselineQuantDefinitionId");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("TensorGroupProfileId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "BaselineQuantDefinitionId", "TensorGroupId");

                    b.HasIndex("ArchitectureFamilyId", "TensorGroupProfileId", "BaselineQuantDefinitionId", "TensorWeightSchemeId", "TensorName")
                        .IsUnique();

                    b.ToTable("LearnedBaselineTensorQuants");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.QuantizationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImatrixDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputModelPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TensorGroupProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("ArchitectureFamilyId");

                    b.HasIndex("ImatrixDefinitionId");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("TensorGroupProfileId");

                    b.ToTable("QuantizationRuns");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.TensorCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("AttnKV")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnOutput")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnQ")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BaseQuant")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Embeddings")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnDown")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnUpGate")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LmHead")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeExperts")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeRouter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseQuant", "Embeddings", "LmHead", "AttnQ", "AttnKV", "AttnOutput", "FfnUpGate", "FfnDown", "MoeExperts", "MoeRouter")
                        .IsUnique();

                    b.ToTable("TensorCombos");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.TensorGroupProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectureFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureFamilyId", "FingerprintHash")
                        .IsUnique();

                    b.HasIndex("ArchitectureFamilyId", "IsActive");

                    b.ToTable("TensorGroupProfiles");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ImatrixDefinition", "ImatrixDefinition")
                        .WithMany()
                        .HasForeignKey("ImatrixDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("ImatrixDefinition");

                    b.Navigation("TensorCombo");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmarkLearnedSource", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany("LearnedSources")
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.BaselineQuantDefinition", "BaselineQuantDefinition")
                        .WithMany()
                        .HasForeignKey("BaselineQuantDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "SourceLearningBenchmark")
                        .WithMany()
                        .HasForeignKey("SourceLearningBenchmarkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiBenchmark");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("BaselineQuantDefinition");

                    b.Navigation("SourceLearningBenchmark");

                    b.Navigation("TensorCombo");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyInteractionRule", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ImatrixDefinition", "ImatrixDefinition")
                        .WithMany()
                        .HasForeignKey("ImatrixDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("ImatrixDefinition");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyInteractionRuleGroupState", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AnomalyInteractionRule", "Rule")
                        .WithMany("GroupStates")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyProbeObservation", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ImatrixDefinition", "ImatrixDefinition")
                        .WithMany()
                        .HasForeignKey("ImatrixDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "ProbeTensorCombo")
                        .WithMany()
                        .HasForeignKey("ProbeTensorComboId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "ReferenceTensorCombo")
                        .WithMany()
                        .HasForeignKey("ReferenceTensorComboId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.AnomalyProbeSession", "Session")
                        .WithMany("Observations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("ImatrixDefinition");

                    b.Navigation("ProbeTensorCombo");

                    b.Navigation("ReferenceTensorCombo");

                    b.Navigation("Session");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyProbeSession", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ImatrixDefinition", "ImatrixDefinition")
                        .WithMany()
                        .HasForeignKey("ImatrixDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("ImatrixDefinition");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.ArchitectureFamilyModelHash", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.BaselineQuantDefinition", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ArchitectureFamily");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.BenchmarkRun", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany()
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.CategoryBenchmark", "CategoryBenchmark")
                        .WithMany()
                        .HasForeignKey("CategoryBenchmarkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MQ.DB.Models.DbModels.ImatrixDefinition", "ImatrixDefinition")
                        .WithMany()
                        .HasForeignKey("ImatrixDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiBenchmark");

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("CategoryBenchmark");

                    b.Navigation("ImatrixDefinition");

                    b.Navigation("TensorCombo");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.CategoryBenchmark", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany("CategorBenchmarks")
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiBenchmark");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.ExecutionPlanProbeCache", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ImatrixDefinition", "ImatrixDefinition")
                        .WithMany()
                        .HasForeignKey("ImatrixDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("ImatrixDefinition");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.ImatrixDefinition", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiModelHash");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.LearnedBaselineTensorQuant", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany()
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.BaselineQuantDefinition", "BaselineQuantDefinition")
                        .WithMany()
                        .HasForeignKey("BaselineQuantDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiBenchmark");

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("BaselineQuantDefinition");

                    b.Navigation("TensorCombo");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.QuantizationRun", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany()
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.ImatrixDefinition", "ImatrixDefinition")
                        .WithMany()
                        .HasForeignKey("ImatrixDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorGroupProfile", "TensorGroupProfile")
                        .WithMany()
                        .HasForeignKey("TensorGroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiBenchmark");

                    b.Navigation("AiModelHash");

                    b.Navigation("ArchitectureFamily");

                    b.Navigation("ImatrixDefinition");

                    b.Navigation("TensorCombo");

                    b.Navigation("TensorGroupProfile");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.TensorGroupProfile", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.ArchitectureFamily", "ArchitectureFamily")
                        .WithMany()
                        .HasForeignKey("ArchitectureFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchitectureFamily");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.Navigation("CategorBenchmarks");

                    b.Navigation("LearnedSources");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyInteractionRule", b =>
                {
                    b.Navigation("GroupStates");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AnomalyProbeSession", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
