// <auto-generated />
using MQ.DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MQ.DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101211347_tablechanges")]
    partial class tablechanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiModelHashToId", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniqueHash");

                    b.ToTable("AiModelHashToId");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.TensorCombo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnKV")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnOutput")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnQ")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BaseQuant")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Embeddings")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnDown")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnUpGate")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LmHead")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeExperts")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeRouter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseQuant", "Embeddings", "LmHead", "AttnQ", "AttnKV", "AttnOutput", "FfnUpGate", "FfnDown", "MoeExperts", "MoeRouter")
                        .IsUnique();

                    b.ToTable("TensorCombo");
                });
#pragma warning restore 612, 618
        }
    }
}
