// <auto-generated />
using System;
using MQ.DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MQ.DB.Migrations
{
    [DbContext(typeof(MagicQuantContext))]
    [Migration("20260416203656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Ngl")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.Property<double>("TokensPerSecond")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("AiModelHashId", "TensorComboId")
                        .IsUnique();

                    b.ToTable("AiBenchmarks");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiModelHash", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniqueHash");

                    b.ToTable("AiModelHashes");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.BaselineQuantDefinition", b =>
                {
                    b.Property<byte>("BaselineQuantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte>("DefaultTensorSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultTensorSchemeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("BaselineQuantId");

                    b.HasIndex("BaselineName")
                        .IsUnique();

                    b.HasIndex("DefaultTensorSchemeId")
                        .IsUnique();

                    b.HasIndex("DefaultTensorSchemeName")
                        .IsUnique();

                    b.ToTable("BaselineQuantDefinitions");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.BenchmarkRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CategoryBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("CategoryBenchmarkId");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("AiBenchmarkId", "Category");

                    b.ToTable("BenchmarkRuns");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.CategoryBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kld")
                        .HasColumnType("REAL");

                    b.Property<double>("Ppl")
                        .HasColumnType("REAL");

                    b.Property<double>("PplError")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.ToTable("CategoryBenchmark");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.LearnedBaselineTensorQuant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BaselineQuantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalQuantType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte>("TensorGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TensorName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<byte>("TensorWeightSchemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.HasIndex("AiModelHashId", "BaselineQuantId", "TensorWeightSchemeId", "TensorGroupId");

                    b.HasIndex("AiModelHashId", "BaselineQuantId", "TensorWeightSchemeId", "TensorName")
                        .IsUnique();

                    b.ToTable("LearnedBaselineTensorQuants");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.QuantizationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AiBenchmarkId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputModelPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TensorComboId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.HasIndex("AiModelHashId");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("TensorComboId");

                    b.ToTable("QuantizationRuns");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.TensorCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("AttnKV")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnOutput")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnQ")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BaseQuant")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Embeddings")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnDown")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnUpGate")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LmHead")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeExperts")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeRouter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseQuant", "Embeddings", "LmHead", "AttnQ", "AttnKV", "AttnOutput", "FfnUpGate", "FfnDown", "MoeExperts", "MoeRouter")
                        .IsUnique();

                    b.ToTable("TensorCombos");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("TensorCombo");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.BenchmarkRun", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany()
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.CategoryBenchmark", "CategoryBenchmark")
                        .WithMany()
                        .HasForeignKey("CategoryBenchmarkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiBenchmark");

                    b.Navigation("AiModelHash");

                    b.Navigation("CategoryBenchmark");

                    b.Navigation("TensorCombo");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.CategoryBenchmark", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany("CategorBenchmarks")
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiBenchmark");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.LearnedBaselineTensorQuant", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany()
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiBenchmark");

                    b.Navigation("AiModelHash");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.QuantizationRun", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany()
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiBenchmark");

                    b.Navigation("AiModelHash");

                    b.Navigation("TensorCombo");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.Navigation("CategorBenchmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
