// <auto-generated />
using MQ.DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MQ.DB.Migrations
{
    [DbContext(typeof(MagicQuantContext))]
    partial class MagicQuantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AiModelHashId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Ngl")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TensorComboId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TokensPerSecond")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TensorComboId");

                    b.HasIndex("AiModelHashId", "TensorComboId")
                        .IsUnique();

                    b.ToTable("AiBenchmarks");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiModelHash", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniqueHash");

                    b.ToTable("AiModelHashes");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.CategoryBenchmark", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AiBenchmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AiBenchmarkId1")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kld")
                        .HasColumnType("REAL");

                    b.Property<double>("Ppl")
                        .HasColumnType("REAL");

                    b.Property<double>("PplError")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AiBenchmarkId");

                    b.HasIndex("AiBenchmarkId1");

                    b.ToTable("CategoryBenchmark");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.TensorCombo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnKV")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnOutput")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttnQ")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BaseQuant")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Embeddings")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnDown")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FfnUpGate")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LmHead")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeExperts")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MoeRouter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseQuant", "Embeddings", "LmHead", "AttnQ", "AttnKV", "AttnOutput", "FfnUpGate", "FfnDown", "MoeExperts", "MoeRouter")
                        .IsUnique();

                    b.ToTable("TensorCombos");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiModelHash", "AiModelHash")
                        .WithMany()
                        .HasForeignKey("AiModelHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.TensorCombo", "TensorCombo")
                        .WithMany()
                        .HasForeignKey("TensorComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModelHash");

                    b.Navigation("TensorCombo");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.CategoryBenchmark", b =>
                {
                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", null)
                        .WithMany("CategorBenchmarks")
                        .HasForeignKey("AiBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MQ.DB.Models.DbModels.AiBenchmark", "AiBenchmark")
                        .WithMany()
                        .HasForeignKey("AiBenchmarkId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiBenchmark");
                });

            modelBuilder.Entity("MQ.DB.Models.DbModels.AiBenchmark", b =>
                {
                    b.Navigation("CategorBenchmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
