using MagicQuant.Configuration;
using Microsoft.EntityFrameworkCore;
using MQ.DB;
using MQ.DB.Data;
using MQ.DB.Models;
using MQ.DB.Models.DbModels;
using Spectre.Console;

namespace MagicQuant.Services;

public sealed class TargetedRelearnService
{
    public async Task PlanConfirmAndExecuteAsync(IReadOnlyCollection<ResolvedCustomBaselineSpec> resolvedCustomBaselines, CancellationToken ct = default)
    {
        int architectureFamilyId = TensorGroupProfileService.RequireCurrentArchitectureFamilyId();
        int tensorGroupProfileId = TensorGroupProfileService.RequireCurrentProfileId();

        await using var db = new MagicQuantContext();
        var plan = new TargetedRelearnPlan(architectureFamilyId, tensorGroupProfileId);

        if (Config.Current.Learning.ForceRelearnArchitectureFamily)
        {
            plan.ArchitectureFamilyWide = true;
        }

        foreach (var raw in Config.Current.Learning.ForceRelearnStandardBaselines ?? [])
        {
            if (string.IsNullOrWhiteSpace(raw))
                continue;

            var baseline = BaselineQuants.ResolveBuiltInStandardBaseline(raw.Trim())
                ?? throw new InvalidOperationException($"Unknown standard baseline '{raw}' in learning.force_relearn_standard_baselines.");

            var definition = await db.BaselineQuantDefinitions.AsNoTracking().FirstOrDefaultAsync(x =>
                x.ArchitectureFamilyId == null && x.RuntimeBaselineId == baseline.UniqueId, ct);

            if (definition == null)
                throw new InvalidOperationException($"SQLite baseline definition was not found for standard baseline '{raw}'.");

            plan.BaselineDefinitionIds.Add(definition.Id);
            plan.TargetDescriptions.Add($"standard:{definition.DisplayName}");
        }

        foreach (var spec in resolvedCustomBaselines.Where(x => x.ForceRelearn))
        {
            var definition = await db.BaselineQuantDefinitions.AsNoTracking().FirstOrDefaultAsync(x =>
                x.ArchitectureFamilyId == architectureFamilyId &&
                x.RuntimeBaselineId == spec.DynamicBaselineId, ct);

            if (definition == null)
                throw new InvalidOperationException($"Custom include requested force_relearn, but no DB definition was found for '{spec.RepoId}/{spec.SourceFileName}'.");

            plan.BaselineDefinitionIds.Add(definition.Id);
            plan.TargetDescriptions.Add($"custom:{definition.SourceRepository}/{definition.SourceFileName}");
        }

        if (!plan.HasTargets)
            return;

        await PopulateCountsAsync(db, plan, ct);
        PrintPlan(plan);

        if (!AnsiConsole.Confirm("Apply this targeted destructive relearn plan?", defaultValue: false))
        {
            throw new OperationCanceledException("Targeted relearn was declined by the user. Aborting before any destructive changes.");
        }

        await ExecuteAsync(db, plan, ct);
        AnsiConsole.MarkupLine("[green]Targeted relearn cleanup complete.[/] The affected truth will be regenerated by this run.");
    }

    private static async Task PopulateCountsAsync(MagicQuantContext db, TargetedRelearnPlan plan, CancellationToken ct)
    {
        IQueryable<AiBenchmark> benchmarkQuery = BuildAffectedBenchmarkQuery(db, plan);
        var benchmarkIds = await benchmarkQuery.Select(x => x.Id).Distinct().ToListAsync(ct);

        plan.AiBenchmarkRows = benchmarkIds.Count;
        plan.CategoryBenchmarkRows = await db.Set<CategoryBenchmark>().CountAsync(x => benchmarkIds.Contains(x.AiBenchmarkId), ct);
        plan.BenchmarkRunRows = await db.BenchmarkRuns.CountAsync(x => benchmarkIds.Contains(x.AiBenchmarkId), ct);
        plan.QuantizationRunRowsToDetach = await db.QuantizationRuns.CountAsync(x => x.AiBenchmarkId != null && benchmarkIds.Contains(x.AiBenchmarkId.Value), ct);
        plan.AiBenchmarkLearnedSourceRows = await db.AiBenchmarkLearnedSources.CountAsync(x => benchmarkIds.Contains(x.AiBenchmarkId), ct);

        if (plan.ArchitectureFamilyWide)
        {
            plan.LearnedBaselineTensorQuantRows = await db.LearnedBaselineTensorQuants
                .CountAsync(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId, ct);
            plan.ExecutionPlanProbeCacheRows = await db.ExecutionPlanProbeCaches
                .CountAsync(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId, ct);
        }
        else
        {
            plan.LearnedBaselineTensorQuantRows = await db.LearnedBaselineTensorQuants
                .CountAsync(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId &&
                                 x.TensorGroupProfileId == plan.TensorGroupProfileId &&
                                 plan.BaselineDefinitionIds.Contains(x.BaselineQuantDefinitionId), ct);
            plan.ExecutionPlanProbeCacheRows = await db.ExecutionPlanProbeCaches
                .CountAsync(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId &&
                                 x.TensorGroupProfileId == plan.TensorGroupProfileId, ct);
        }
    }

    private static void PrintPlan(TargetedRelearnPlan plan)
    {
        AnsiConsole.Write(new Rule("[red]Targeted Relearn Deletion Plan[/]") { Justification = Justify.Left });
        if (plan.ArchitectureFamilyWide)
            AnsiConsole.MarkupLine("[yellow]Scope:[/] active architecture family, all tensor group profiles");
        else
            AnsiConsole.MarkupLine($"[yellow]Scope:[/] active architecture family + tensor group profile id [cyan]{plan.TensorGroupProfileId}[/]");

        foreach (var target in plan.TargetDescriptions.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x => x))
            AnsiConsole.MarkupLine($"  [grey]- {Markup.Escape(target)}[/]");

        AnsiConsole.MarkupLine($"[red]LearnedBaselineTensorQuant rows:[/] {plan.LearnedBaselineTensorQuantRows:N0}");
        AnsiConsole.MarkupLine($"[red]AiBenchmark rows:[/] {plan.AiBenchmarkRows:N0}");
        AnsiConsole.MarkupLine($"[red]CategoryBenchmark rows:[/] {plan.CategoryBenchmarkRows:N0}");
        AnsiConsole.MarkupLine($"[red]BenchmarkRun rows:[/] {plan.BenchmarkRunRows:N0}");
        AnsiConsole.MarkupLine($"[yellow]QuantizationRun rows to detach:[/] {plan.QuantizationRunRowsToDetach:N0}");
        AnsiConsole.MarkupLine($"[red]AiBenchmarkLearnedSource rows:[/] {plan.AiBenchmarkLearnedSourceRows:N0}");
        AnsiConsole.MarkupLine($"[red]ExecutionPlanProbeCache rows:[/] {plan.ExecutionPlanProbeCacheRows:N0}");
    }

    private static async Task ExecuteAsync(MagicQuantContext db, TargetedRelearnPlan plan, CancellationToken ct)
    {
        await using var transaction = await db.Database.BeginTransactionAsync(ct);

        IQueryable<AiBenchmark> benchmarkQuery = BuildAffectedBenchmarkQuery(db, plan);
        var benchmarkIds = await benchmarkQuery.Select(x => x.Id).Distinct().ToListAsync(ct);

        if (benchmarkIds.Count > 0)
        {
            await db.QuantizationRuns
                .Where(x => x.AiBenchmarkId != null && benchmarkIds.Contains(x.AiBenchmarkId.Value))
                .ExecuteUpdateAsync(x => x.SetProperty(r => r.AiBenchmarkId, (Guid?)null), ct);

            await db.AiBenchmarks
                .Where(x => benchmarkIds.Contains(x.Id))
                .ExecuteDeleteAsync(ct);
        }

        if (plan.ArchitectureFamilyWide)
        {
            await db.LearnedBaselineTensorQuants
                .Where(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId)
                .ExecuteDeleteAsync(ct);

            await db.ExecutionPlanProbeCaches
                .Where(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId)
                .ExecuteDeleteAsync(ct);
        }
        else
        {
            await db.LearnedBaselineTensorQuants
                .Where(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId &&
                            x.TensorGroupProfileId == plan.TensorGroupProfileId &&
                            plan.BaselineDefinitionIds.Contains(x.BaselineQuantDefinitionId))
                .ExecuteDeleteAsync(ct);

            await db.ExecutionPlanProbeCaches
                .Where(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId &&
                            x.TensorGroupProfileId == plan.TensorGroupProfileId)
                .ExecuteDeleteAsync(ct);
        }

        await transaction.CommitAsync(ct);
    }

    private static IQueryable<AiBenchmark> BuildAffectedBenchmarkQuery(MagicQuantContext db, TargetedRelearnPlan plan)
    {
        if (plan.ArchitectureFamilyWide)
            return db.AiBenchmarks.Where(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId);

        var pureBaselineRuntimeIds = db.BaselineQuantDefinitions
            .Where(x => plan.BaselineDefinitionIds.Contains(x.Id))
            .Select(x => x.RuntimeBaselineId)
            .ToList();

        var pureBaselineBenchmarks = db.AiBenchmarks
            .Include(x => x.TensorCombo)
            .Where(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId &&
                        x.TensorGroupProfileId == plan.TensorGroupProfileId &&
                        pureBaselineRuntimeIds.Contains(x.TensorCombo.BaseQuant) &&
                        x.TensorCombo.Embeddings == 0 && x.TensorCombo.LmHead == 0 &&
                        x.TensorCombo.AttnQ == 0 && x.TensorCombo.AttnKV == 0 &&
                        x.TensorCombo.AttnOutput == 0 && x.TensorCombo.FfnUpGate == 0 &&
                        x.TensorCombo.FfnDown == 0 && x.TensorCombo.MoeExperts == 0 &&
                        x.TensorCombo.MoeRouter == 0);

        var dependentHybridBenchmarkIds = db.AiBenchmarkLearnedSources
            .Where(x => x.ArchitectureFamilyId == plan.ArchitectureFamilyId &&
                        x.TensorGroupProfileId == plan.TensorGroupProfileId &&
                        plan.BaselineDefinitionIds.Contains(x.BaselineQuantDefinitionId))
            .Select(x => x.AiBenchmarkId);

        var dependentHybridBenchmarks = db.AiBenchmarks
            .Where(x => dependentHybridBenchmarkIds.Contains(x.Id));

        return pureBaselineBenchmarks.Concat(dependentHybridBenchmarks);
    }

    private sealed class TargetedRelearnPlan
    {
        public TargetedRelearnPlan(int architectureFamilyId, int tensorGroupProfileId)
        {
            ArchitectureFamilyId = architectureFamilyId;
            TensorGroupProfileId = tensorGroupProfileId;
        }

        public int ArchitectureFamilyId { get; }
        public int TensorGroupProfileId { get; }
        public bool ArchitectureFamilyWide { get; set; }
        public HashSet<int> BaselineDefinitionIds { get; } = new();
        public List<string> TargetDescriptions { get; } = new();
        public bool HasTargets => ArchitectureFamilyWide || BaselineDefinitionIds.Count > 0;
        public int LearnedBaselineTensorQuantRows { get; set; }
        public int AiBenchmarkRows { get; set; }
        public int CategoryBenchmarkRows { get; set; }
        public int BenchmarkRunRows { get; set; }
        public int QuantizationRunRowsToDetach { get; set; }
        public int AiBenchmarkLearnedSourceRows { get; set; }
        public int ExecutionPlanProbeCacheRows { get; set; }
    }
}
